export * from './Home';
export * from './auth';
export * from './buscar';
export * from './equipo';
export * from './liga';
export * from './partido';
export * from './partidos';
export * from './about';
export * from './contact';
export * from './proyecto';
export * from './equipos'
export * from './ligas'